# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransferProtocal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransferProtocal.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16TransferProtocal.proto\"\x94\x01\n\x0bRequestType\x12\x0f\n\x07request\x18\x01 \x01(\x05\"t\n\x04Type\x12\x08\n\x04None\x10\x00\x12\r\n\tLOGIN_REQ\x10\x01\x12\x14\n\x10SAVE_ARCHIVE_REQ\x10\x02\x12\x13\n\x0fGET_ARCHIVE_REQ\x10\x03\x12\x16\n\x12\x44\x45LETE_ARCHIVE_REQ\x10\x04\x12\x10\n\x0cREGISTER_REQ\x10\x05\"\xa4\x01\n\nResultType\x12 \n\x06result\x18\x01 \x01(\x0e\x32\x10.ResultType.Type\"t\n\x04Type\x12\x08\n\x04None\x10\x00\x12\r\n\tLOGIN_RES\x10\x01\x12\x14\n\x10SAVE_ARCHIVE_RES\x10\x02\x12\x13\n\x0fGET_ARCHIVE_RES\x10\x03\x12\x16\n\x12\x44\x45LETE_ARCHIVE_RES\x10\x04\x12\x10\n\x0cREGISTER_RES\x10\x05\":\n\x07\x41\x63\x63ount\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x87\x01\n\x0bRegisterRes\x12\x12\n\nhasSucceed\x18\x01 \x01(\x08\x12%\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x16.RegisterRes.ErrorType\"=\n\tErrorType\x12\x08\n\x04None\x10\x00\x12\r\n\tUSER_EXIT\x10\x01\x12\x17\n\x13INVALIDATED_ACCOUNT\x10\x02\"\x8c\x01\n\x08LoginRes\x12\x12\n\nhasSucceed\x18\x01 \x01(\x08\x12\"\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x13.LoginRes.ErrorType\"H\n\tErrorType\x12\x08\n\x04None\x10\x00\x12\x18\n\x14INVALIDATED_PASSWORD\x10\x01\x12\x17\n\x13INVALIDATED_ACCOUNT\x10\x02\"\x8b\x01\n\x0c\x41rchiveOpRes\x12\x12\n\nhasSucceed\x18\x01 \x01(\x08\x12\'\n\toperation\x18\x02 \x01(\x0e\x32\x14.ArchiveOpRes.OpType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"0\n\x06OpType\x12\x08\n\x04None\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\x07\n\x03\x41\x44\x44\x10\x02\x12\x07\n\x03GET\x10\x03\x62\x06proto3')
)



_REQUESTTYPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='RequestType.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_REQ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAVE_ARCHIVE_REQ', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_ARCHIVE_REQ', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ARCHIVE_REQ', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_REQ', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=59,
  serialized_end=175,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE_TYPE)

_RESULTTYPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='ResultType.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_RES', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAVE_ARCHIVE_RES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_ARCHIVE_RES', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ARCHIVE_RES', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_RES', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_RESULTTYPE_TYPE)

_REGISTERRES_ERRORTYPE = _descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='RegisterRes.ErrorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_EXIT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALIDATED_ACCOUNT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=479,
  serialized_end=540,
)
_sym_db.RegisterEnumDescriptor(_REGISTERRES_ERRORTYPE)

_LOGINRES_ERRORTYPE = _descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='LoginRes.ErrorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALIDATED_PASSWORD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALIDATED_ACCOUNT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=611,
  serialized_end=683,
)
_sym_db.RegisterEnumDescriptor(_LOGINRES_ERRORTYPE)

_ARCHIVEOPRES_OPTYPE = _descriptor.EnumDescriptor(
  name='OpType',
  full_name='ArchiveOpRes.OpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=777,
  serialized_end=825,
)
_sym_db.RegisterEnumDescriptor(_ARCHIVEOPRES_OPTYPE)


_REQUESTTYPE = _descriptor.Descriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='RequestType.request', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTTYPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=175,
)


_RESULTTYPE = _descriptor.Descriptor(
  name='ResultType',
  full_name='ResultType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ResultType.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESULTTYPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=342,
)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='Account.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='Account.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Account.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=402,
)


_REGISTERRES = _descriptor.Descriptor(
  name='RegisterRes',
  full_name='RegisterRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hasSucceed', full_name='RegisterRes.hasSucceed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='RegisterRes.error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTERRES_ERRORTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=540,
)


_LOGINRES = _descriptor.Descriptor(
  name='LoginRes',
  full_name='LoginRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hasSucceed', full_name='LoginRes.hasSucceed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='LoginRes.error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGINRES_ERRORTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=683,
)


_ARCHIVEOPRES = _descriptor.Descriptor(
  name='ArchiveOpRes',
  full_name='ArchiveOpRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hasSucceed', full_name='ArchiveOpRes.hasSucceed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='ArchiveOpRes.operation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ArchiveOpRes.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARCHIVEOPRES_OPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=825,
)

_REQUESTTYPE_TYPE.containing_type = _REQUESTTYPE
_RESULTTYPE.fields_by_name['result'].enum_type = _RESULTTYPE_TYPE
_RESULTTYPE_TYPE.containing_type = _RESULTTYPE
_REGISTERRES.fields_by_name['error'].enum_type = _REGISTERRES_ERRORTYPE
_REGISTERRES_ERRORTYPE.containing_type = _REGISTERRES
_LOGINRES.fields_by_name['error'].enum_type = _LOGINRES_ERRORTYPE
_LOGINRES_ERRORTYPE.containing_type = _LOGINRES
_ARCHIVEOPRES.fields_by_name['operation'].enum_type = _ARCHIVEOPRES_OPTYPE
_ARCHIVEOPRES_OPTYPE.containing_type = _ARCHIVEOPRES
DESCRIPTOR.message_types_by_name['RequestType'] = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['ResultType'] = _RESULTTYPE
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['RegisterRes'] = _REGISTERRES
DESCRIPTOR.message_types_by_name['LoginRes'] = _LOGINRES
DESCRIPTOR.message_types_by_name['ArchiveOpRes'] = _ARCHIVEOPRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestType = _reflection.GeneratedProtocolMessageType('RequestType', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTTYPE,
  __module__ = 'TransferProtocal_pb2'
  # @@protoc_insertion_point(class_scope:RequestType)
  ))
_sym_db.RegisterMessage(RequestType)

ResultType = _reflection.GeneratedProtocolMessageType('ResultType', (_message.Message,), dict(
  DESCRIPTOR = _RESULTTYPE,
  __module__ = 'TransferProtocal_pb2'
  # @@protoc_insertion_point(class_scope:ResultType)
  ))
_sym_db.RegisterMessage(ResultType)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'TransferProtocal_pb2'
  # @@protoc_insertion_point(class_scope:Account)
  ))
_sym_db.RegisterMessage(Account)

RegisterRes = _reflection.GeneratedProtocolMessageType('RegisterRes', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERRES,
  __module__ = 'TransferProtocal_pb2'
  # @@protoc_insertion_point(class_scope:RegisterRes)
  ))
_sym_db.RegisterMessage(RegisterRes)

LoginRes = _reflection.GeneratedProtocolMessageType('LoginRes', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRES,
  __module__ = 'TransferProtocal_pb2'
  # @@protoc_insertion_point(class_scope:LoginRes)
  ))
_sym_db.RegisterMessage(LoginRes)

ArchiveOpRes = _reflection.GeneratedProtocolMessageType('ArchiveOpRes', (_message.Message,), dict(
  DESCRIPTOR = _ARCHIVEOPRES,
  __module__ = 'TransferProtocal_pb2'
  # @@protoc_insertion_point(class_scope:ArchiveOpRes)
  ))
_sym_db.RegisterMessage(ArchiveOpRes)


# @@protoc_insertion_point(module_scope)
